/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container": "#201f22",
        "on-primary-fixed-variant": "#4d3d76",
        "surface-container-high": "#2a2a2c",
        "tertiary-container": "#ffaaf3",
        "on-primary-container": "#594983",
        "background": "#131315",
        "tertiary-fixed-dim": "#ffabf3",
        "primary-container": "#d0bcff",
        "on-surface-variant": "#cac4d0",
        "on-tertiary-fixed": "#380038",
        "on-secondary-fixed-variant": "#004f58",
        "on-primary-fixed": "#210f48",
        "surface-container-lowest": "#0e0e10",
        "on-tertiary-fixed-variant": "#810081",
        "inverse-surface": "#e5e1e4",
        "surface-variant": "#353437",
        "tertiary": "#ffd6f5",
        "primary": "#e9ddff",
        "on-secondary-fixed": "#001f24",
        "on-secondary": "#00363d",
        "on-secondary-container": "#00616d",
        "on-surface": "#e5e1e4",
        "surface": "#131315",
        "secondary": "#bef4ff",
        "on-primary": "#37265e",
        "outline-variant": "#49454f",
        "surface-container-low": "#1c1b1d",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#d0bcff",
        "secondary-fixed-dim": "#00daf3",
        "error-container": "#93000a",
        "secondary-fixed": "#9cefff",
        "surface-tint": "#d0bcff",
        "secondary-container": "#01e3fd",
        "tertiary-fixed": "#ffd7f5",
        "on-background": "#e5e1e4",
        "surface-container-highest": "#353437",
        "on-tertiary": "#5b005b",
        "primary-fixed": "#e9ddff",
        "on-tertiary-container": "#940094",
        "outline": "#948f9a",
        "inverse-primary": "#665590",
        "surface-dim": "#131315",
        "inverse-on-surface": "#313032",
        "surface-bright": "#39393b",
        "error": "#ffb4ab",
        "on-error": "#690005"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
    },
  },
  plugins: [],
}
